### ISSUE TITLE
[Question] Engine

### ISSUE THREAD

**Issue by scriptingstudio** [jdhitsolutions/ScheduledJobTools#1]
Hello,

I could not find any clear answer on my question. May be you know it.
Does ScheduledJob imply that PS host is always in memory or it is created every time?

**Comment by jdhitsolutions** [comment]
A scheduled job is actually a scheduled task that runs your PowerShell code at the specified time.

**Comment by scriptingstudio** [comment]
that is, the scheduler starts PS host every time?

**Comment by jdhitsolutions** [comment]
Yes. That task scheduler is in charge. At the scheduled time it spins up an instance of PowerShell to run your code. You could do the same thing manually with the Scheduled Tasks module, but Scheduled Jobs make it easier.

**Comment by scriptingstudio** [comment]
thanks a lot
